

services:

  proyecto:
    build: Proyecto
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/sport-gimnasio?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
      SPRING_MAIL_HOST: "smtp.gmail.com"
      SPRING_MAIL_PORT: "587"
      SPRING_MAIL_USERNAME: "mailprueba041@gmail.com"
      SPRING_MAIL_PASSWORD: "vyif enya jurs pybo"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
      MERCADOPAGO_ACCESS_TOKEN: ${MERCADOPAGO_ACCESS_TOKEN}
      MERCADOPAGO_PAYMENT_VALIDATION_SECRET: ${MERCADOPAGO_PAYMENT_VALIDATION_SECRET}
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: sport-gimnasio
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost","-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: